apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: namespace-name
  name: pv
  labels:
    type: pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/logs"
