apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev-zj
  name: pvc
  labels:
    name: pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi