apiVersion: v1
kind: Secret
metadata:
  namespace: dev-zj
  name: hssk-secret
  labels:
    app: hssk-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1iZWlqaW5nLmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6Inl3czEzMDYwODQzNjciLCJwYXNzd29yZCI6Ill3czE5OTQwNjE4Nzc5MyIsImVtYWlsIjoiMTMwNjA4NDM2N0BxcS5jb20iLCJhdXRoIjoiZVhkek1UTXdOakE0TkRNMk56cFpkM014T1RrME1EWXhPRGMzT1RNPSJ9fX0=
  #对dockerconfig.json进行编码 注意dockerconfig.json文件中不能有空格 可以使用cat dockerconfig.json | base64得到
  #dockerconfig.json中auth是通过base64(username:password)得到的